<?php

declare(strict_types=1);

namespace App\Repositories\Base;

use App\Models\Contact;
use Celeris\Framework\Database\Connection\ConnectionInterface;
use Celeris\Framework\Database\DBAL;
use RuntimeException;

/**
 * @generated by Celeris scaffolding. Do not edit directly.
 * Extend this class in `App\Repositories\ContactRepository`.
 */
class ContactRepositoryBase
{
   private ?ConnectionInterface $connection = null;
   private string $connectionName;
   private bool $useJsonStorage;
   private string $storagePath;
   private ?string $fallbackStoragePath = null;

   public function __construct(
      private ?DBAL $dbal = null,
      ?string $storagePath = null,
   )
   {
      $this->connectionName = $this->resolveConfiguredConnection();
      $this->useJsonStorage = $this->connectionName === '';
      $this->storagePath = $storagePath ?? dirname(__DIR__, 3) . '/var/data/contacts.json';
   }

   /** @return array<int, Contact> */
   public function all(): array
   {
      if (!$this->useJsonStorage) {
         return $this->allFromDatabase();
      }

      return array_map(
         static fn (array $row): Contact => new Contact(
            (int) ($row['id'] ?? 0),
            (string) ($row['firstName'] ?? ''),
            (string) ($row['lastName'] ?? ''),
            (string) ($row['phone'] ?? ''),
            (string) ($row['address'] ?? ''),
            (int) ($row['age'] ?? 0),
         ),
         $this->dataRows(),
      );
   }

   public function find(int $id): ?Contact
   {
      if (!$this->useJsonStorage) {
         return $this->findFromDatabase($id);
      }

      foreach ($this->all() as $contact) {
         if ($contact->id === $id) {
            return $contact;
         }
      }

      return null;
   }

   /**
    * @param array{firstName:string,lastName:string,phone:string,address:string,age:int} $payload
    */
   public function create(array $payload): Contact
   {
      if (!$this->useJsonStorage) {
         return $this->createInDatabase($payload);
      }

      $rows = $this->dataRows();
      $maxId = 0;
      foreach ($rows as $row) {
         $maxId = max($maxId, (int) ($row['id'] ?? 0));
      }

      $record = [
         'id' => $maxId + 1,
         'firstName' => $payload['firstName'],
         'lastName' => $payload['lastName'],
         'phone' => $payload['phone'],
         'address' => $payload['address'],
         'age' => $payload['age'],
      ];

      $rows[] = $record;
      $this->persistRows($rows);

      return new Contact(
         (int) $record['id'],
         (string) $record['firstName'],
         (string) $record['lastName'],
         (string) $record['phone'],
         (string) $record['address'],
         (int) $record['age'],
      );
   }

   /**
    * @param array{firstName:string,lastName:string,phone:string,address:string,age:int} $payload
    */
   public function update(int $id, array $payload): ?Contact
   {
      if (!$this->useJsonStorage) {
         return $this->updateInDatabase($id, $payload);
      }

      $rows = $this->dataRows();
      foreach ($rows as $index => $row) {
         if ((int) ($row['id'] ?? 0) !== $id) {
            continue;
         }

         $rows[$index] = [
            'id' => $id,
            'firstName' => $payload['firstName'],
            'lastName' => $payload['lastName'],
            'phone' => $payload['phone'],
            'address' => $payload['address'],
            'age' => $payload['age'],
         ];
         $this->persistRows($rows);

         return new Contact(
            $id,
            $payload['firstName'],
            $payload['lastName'],
            $payload['phone'],
            $payload['address'],
            $payload['age'],
         );
      }

      return null;
   }

   public function delete(int $id): bool
   {
      if (!$this->useJsonStorage) {
         return $this->deleteInDatabase($id);
      }

      $rows = $this->dataRows();
      $initialCount = count($rows);
      $filtered = array_values(array_filter(
         $rows,
         static fn (array $row): bool => (int) ($row['id'] ?? 0) !== $id
      ));

      if (count($filtered) === $initialCount) {
         return false;
      }

      $this->persistRows($filtered);
      return true;
   }

   /**
    * @return array<int, array{id:int,firstName:string,lastName:string,phone:string,address:string,age:int}>
    */
   private function dataRows(): array
   {
      $path = $this->readPath();
      if (!is_file($path)) {
         return $this->defaultRows();
      }

      $raw = @file_get_contents($path);
      if ($raw === false || trim($raw) === '') {
         return $this->defaultRows();
      }

      $decoded = json_decode($raw, true);
      if (!is_array($decoded)) {
         return $this->defaultRows();
      }

      $rows = [];
      foreach ($decoded as $row) {
         if (!is_array($row)) {
            continue;
         }
         $rows[] = [
            'id' => (int) ($row['id'] ?? 0),
            'firstName' => (string) ($row['firstName'] ?? ''),
            'lastName' => (string) ($row['lastName'] ?? ''),
            'phone' => (string) ($row['phone'] ?? ''),
            'address' => (string) ($row['address'] ?? ''),
            'age' => (int) ($row['age'] ?? 0),
         ];
      }

      return $rows === [] ? $this->defaultRows() : $rows;
   }

   /**
    * @param array<int, array{id:int,firstName:string,lastName:string,phone:string,address:string,age:int}> $rows
    */
   private function persistRows(array $rows): void
   {
      $json = json_encode($rows, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
      if (!is_string($json)) {
         throw new RuntimeException('Failed to encode contacts data.');
      }

      $writeError = null;
      foreach ($this->writeCandidates() as $path) {
         $directory = dirname($path);
         if (!is_dir($directory) && !@mkdir($directory, 0775, true) && !is_dir($directory)) {
            $writeError = sprintf('Failed to create contacts storage directory "%s".', $directory);
            continue;
         }

         if (@file_put_contents($path, $json . "\n", LOCK_EX) !== false) {
            $this->fallbackStoragePath = $path === $this->storagePath ? null : $path;
            return;
         }

         $writeError = sprintf('Failed to write contacts storage file "%s".', $path);
      }

      throw new RuntimeException($writeError ?? 'Failed to persist contacts data.');
   }

   /**
    * @return array<int, array{id:int,firstName:string,lastName:string,phone:string,address:string,age:int}>
    */
   private function defaultRows(): array
   {
      return [
         [
            'id' => 1,
            'firstName' => 'Ada',
            'lastName' => 'Lovelace',
            'phone' => '+1-555-0100',
            'address' => 'Analytical St',
            'age' => 36,
         ],
         [
            'id' => 2,
            'firstName' => 'Grace',
            'lastName' => 'Hopper',
            'phone' => '+1-555-0101',
            'address' => 'Compiler Ave',
            'age' => 37,
         ],
      ];
   }

   /**
    * @return array<int, string>
    */
   private function writeCandidates(): array
   {
      $candidates = [$this->storagePath, $this->tempStoragePath()];
      return array_values(array_unique($candidates));
   }

   private function readPath(): string
   {
      if ($this->fallbackStoragePath !== null && is_file($this->fallbackStoragePath)) {
         return $this->fallbackStoragePath;
      }

      if (is_file($this->storagePath)) {
         return $this->storagePath;
      }

      $tempPath = $this->tempStoragePath();
      if (is_file($tempPath)) {
         $this->fallbackStoragePath = $tempPath;
         return $tempPath;
      }

      return $this->storagePath;
   }

   private function tempStoragePath(): string
   {
      return rtrim(sys_get_temp_dir(), '/\\') . '/celeris-mvc/contacts.json';
   }

   /**
    * @return array<int, Contact>
    */
   private function allFromDatabase(): array
   {
      try {
         $rows = $this->dbConnection()->fetchAll(
            'SELECT id, first_name, last_name, phone, address, age FROM contacts ORDER BY id ASC'
         );
      } catch (\Throwable $exception) {
         throw new RuntimeException('Failed to load contacts from database: ' . $exception->getMessage(), 0, $exception);
      }

      return array_map(static fn (array $row): Contact => self::contactFromDatabaseRow($row), $rows);
   }

   private function findFromDatabase(int $id): ?Contact
   {
      try {
         $row = $this->dbConnection()->fetchOne(
            'SELECT id, first_name, last_name, phone, address, age FROM contacts WHERE id = :id',
            ['id' => $id],
         );
      } catch (\Throwable $exception) {
         throw new RuntimeException('Failed to load contact from database: ' . $exception->getMessage(), 0, $exception);
      }

      return is_array($row) ? self::contactFromDatabaseRow($row) : null;
   }

   /**
    * @param array{firstName:string,lastName:string,phone:string,address:string,age:int} $payload
    */
   private function createInDatabase(array $payload): Contact
   {
      try {
         $connection = $this->dbConnection();
         $connection->execute(
            'INSERT INTO contacts (first_name, last_name, phone, address, age) VALUES (:first_name, :last_name, :phone, :address, :age)',
            [
               'first_name' => $payload['firstName'],
               'last_name' => $payload['lastName'],
               'phone' => $payload['phone'],
               'address' => $payload['address'],
               'age' => $payload['age'],
            ],
         );

         $created = $connection->fetchOne(
            'SELECT id, first_name, last_name, phone, address, age FROM contacts ORDER BY id DESC LIMIT 1'
         );
      } catch (\Throwable $exception) {
         throw new RuntimeException('Failed to create contact in database: ' . $exception->getMessage(), 0, $exception);
      }

      if (!is_array($created)) {
         throw new RuntimeException('Failed to fetch created contact from database.');
      }

      return self::contactFromDatabaseRow($created);
   }

   /**
    * @param array{firstName:string,lastName:string,phone:string,address:string,age:int} $payload
    */
   private function updateInDatabase(int $id, array $payload): ?Contact
   {
      try {
         $affected = $this->dbConnection()->execute(
            'UPDATE contacts SET first_name = :first_name, last_name = :last_name, phone = :phone, address = :address, age = :age WHERE id = :id',
            [
               'id' => $id,
               'first_name' => $payload['firstName'],
               'last_name' => $payload['lastName'],
               'phone' => $payload['phone'],
               'address' => $payload['address'],
               'age' => $payload['age'],
            ],
         );
      } catch (\Throwable $exception) {
         throw new RuntimeException('Failed to update contact in database: ' . $exception->getMessage(), 0, $exception);
      }

      if ($affected < 1) {
         return null;
      }

      return $this->findFromDatabase($id);
   }

   private function deleteInDatabase(int $id): bool
   {
      try {
         $affected = $this->dbConnection()->execute(
            'DELETE FROM contacts WHERE id = :id',
            ['id' => $id],
         );
      } catch (\Throwable $exception) {
         throw new RuntimeException('Failed to delete contact from database: ' . $exception->getMessage(), 0, $exception);
      }

      return $affected > 0;
   }

   private function dbConnection(): ConnectionInterface
   {
      if ($this->connection instanceof ConnectionInterface) {
         return $this->connection;
      }

      if (!$this->dbal instanceof DBAL) {
         throw new RuntimeException('Database connection is configured but DBAL service is unavailable.');
      }

      $this->connection = $this->dbal->connection($this->connectionName);
      return $this->connection;
   }

   private function resolveConfiguredConnection(): string
   {
      $raw = $_ENV['DB_DEFAULT'] ?? $_SERVER['DB_DEFAULT'] ?? getenv('DB_DEFAULT');
      if (!is_scalar($raw)) {
         return '';
      }

      $value = trim((string) $raw);
      if ($value === '' || strtolower($value) === 'null') {
         return '';
      }

      return $value;
   }

   /**
    * @param array<string, mixed> $row
    */
   private static function contactFromDatabaseRow(array $row): Contact
   {
      return new Contact(
         (int) ($row['id'] ?? 0),
         (string) ($row['first_name'] ?? ''),
         (string) ($row['last_name'] ?? ''),
         (string) ($row['phone'] ?? ''),
         (string) ($row['address'] ?? ''),
         (int) ($row['age'] ?? 0),
      );
   }
}
