<?php

declare(strict_types=1);

namespace App\Models\Base;

/**
 * @generated by Celeris scaffolding. Do not edit directly.
 * Extend this class in `App\Models\Contact`.
 */
class ContactBase
{
   public function __construct(
      public int $id,
      public string $firstName,
      public string $lastName,
      public string $phone,
      public string $address,
      public int $age,
   ) {}
}
