<?php

declare(strict_types=1);

namespace App\Services\Base;

use App\Models\Contact;
use App\Repositories\ContactRepository;
use RuntimeException;

/**
 * @generated by Celeris scaffolding. Do not edit directly.
 * Extend this class in `App\Services\ContactService`.
 */
class ContactServiceBase
{
   public function __construct(protected ContactRepository $repository) {}

   /** @return array<int, Contact> */
   public function list(): array
   {
      return $this->repository->all();
   }

   public function getOrFail(int $id): Contact
   {
      $contact = $this->repository->find($id);
      if (!$contact instanceof Contact) {
         throw new RuntimeException('Contact not found.');
      }

      return $contact;
   }
}
