<?php

declare(strict_types=1);

namespace App\Http\Controllers\Base;

use App\Services\ContactService;
use Celeris\Framework\Http\Response;
use Celeris\Framework\Routing\Attribute\Route;
use Celeris\Framework\View\TemplateRendererInterface;

/**
 * @generated by Celeris scaffolding. Do not edit directly.
 * Extend this class in `App\Http\Controllers\ContactPageController`.
 */
class ContactPageControllerBase
{
   public function __construct(
      protected ContactService $service,
      protected TemplateRendererInterface $views,
   ) {}

   #[Route(methods: ['GET'], path: '/', summary: 'Contacts page')]
   public function index(): Response
   {
      $html = $this->renderPage('Contacts', 'contacts/index', [
         'contacts' => $this->service->list(),
      ]);

      return new Response(200, ['content-type' => 'text/html; charset=utf-8'], $html);
   }

   #[Route(methods: ['GET'], path: '/{id}', summary: 'Contact details page')]
   public function show(int $id): Response
   {
      $html = $this->renderPage('Contact', 'contacts/show', [
         'contact' => $this->service->getOrFail($id),
      ]);

      return new Response(200, ['content-type' => 'text/html; charset=utf-8'], $html);
   }

   /**
    * @param array<string, mixed> $data
    */
   protected function renderPage(string $title, string $template, array $data = []): string
   {
      $content = $this->views->render($template, $data);

      return $this->views->render('layout', [
         'title' => $title,
         'content' => $content,
         'username' => $data['username'] ?? 'Guest',
      ]);
   }
}
