<?php

declare(strict_types=1);

namespace App\Http\Controllers\Base;

use App\Services\ContactService;
use Celeris\Framework\Http\Request;
use Celeris\Framework\Http\Response;
use Celeris\Framework\Routing\Attribute\Route;
use Celeris\Framework\View\TemplateRendererInterface;
use InvalidArgumentException;
use RuntimeException;

/**
 * @generated by Celeris scaffolding. Do not edit directly.
 * Extend this class in `App\Http\Controllers\ContactPageController`.
 */
class ContactPageControllerBase
{
   public function __construct(
      protected ContactService $service,
      protected TemplateRendererInterface $views,
   ) {}

   #[Route(methods: ['GET'], path: '/', summary: 'Contacts page')]
   public function index(Request $request): Response
   {
      $html = $this->renderPage('Contacts', 'contacts/index', [
         'contacts' => $this->service->list(),
         'notice' => (string) ($request->getQueryParam('notice', '')),
      ]);

      return new Response(200, ['content-type' => 'text/html; charset=utf-8'], $html);
   }

   #[Route(methods: ['GET'], path: '/create', summary: 'Create contact form')]
   public function createForm(): Response
   {
      $html = $this->renderPage('Add Contact', 'contacts/form', [
         'mode' => 'create',
         'submitLabel' => 'Create Contact',
         'action' => '/contacts/create',
         'values' => [
            'first_name' => '',
            'last_name' => '',
            'phone' => '',
            'address' => '',
            'age' => '',
         ],
         'error' => '',
      ]);

      return new Response(200, ['content-type' => 'text/html; charset=utf-8'], $html);
   }

   #[Route(methods: ['POST'], path: '/create', summary: 'Create contact')]
   public function store(Request $request): Response
   {
      $values = $this->inputValues($request);

      try {
         $this->service->create($this->servicePayload($values));
      } catch (InvalidArgumentException $exception) {
         return $this->renderFormError('Add Contact', '/contacts/create', 'Create Contact', $values, $exception->getMessage());
      } catch (RuntimeException $exception) {
         return $this->renderFormError('Add Contact', '/contacts/create', 'Create Contact', $values, $exception->getMessage());
      }

      return $this->redirect('/contacts?notice=' . rawurlencode('Contact created.'));
   }

   #[Route(methods: ['GET'], path: '/{id}/edit', summary: 'Edit contact form')]
   public function editForm(int $id): Response
   {
      $contact = $this->service->getOrFail($id);
      $html = $this->renderPage('Edit Contact', 'contacts/form', [
         'mode' => 'edit',
         'submitLabel' => 'Save Changes',
         'action' => '/contacts/' . $id . '/edit',
         'values' => [
            'first_name' => $contact->firstName,
            'last_name' => $contact->lastName,
            'phone' => $contact->phone,
            'address' => $contact->address,
            'age' => (string) $contact->age,
         ],
         'error' => '',
      ]);

      return new Response(200, ['content-type' => 'text/html; charset=utf-8'], $html);
   }

   #[Route(methods: ['POST'], path: '/{id}/edit', summary: 'Update contact')]
   public function update(int $id, Request $request): Response
   {
      $values = $this->inputValues($request);

      try {
         $this->service->update($id, $this->servicePayload($values));
      } catch (InvalidArgumentException $exception) {
         return $this->renderFormError('Edit Contact', '/contacts/' . $id . '/edit', 'Save Changes', $values, $exception->getMessage());
      } catch (RuntimeException $exception) {
         if ($exception->getMessage() === 'Contact not found.') {
            return new Response(404, ['content-type' => 'text/plain; charset=utf-8'], $exception->getMessage());
         }

         return $this->renderFormError('Edit Contact', '/contacts/' . $id . '/edit', 'Save Changes', $values, $exception->getMessage());
      }

      return $this->redirect('/contacts?notice=' . rawurlencode('Contact updated.'));
   }

   #[Route(methods: ['POST'], path: '/{id}/delete', summary: 'Delete contact')]
   public function delete(int $id): Response
   {
      try {
         $deleted = $this->service->delete($id);
      } catch (RuntimeException $exception) {
         return $this->redirect('/contacts?notice=' . rawurlencode($exception->getMessage()));
      }

      return $this->redirect('/contacts?notice=' . rawurlencode($deleted ? 'Contact deleted.' : 'Contact not found.'));
   }

   #[Route(methods: ['GET'], path: '/{id}', summary: 'Contact details page')]
   public function show(int $id): Response
   {
      $html = $this->renderPage('Contact', 'contacts/show', [
         'contact' => $this->service->getOrFail($id),
      ]);

      return new Response(200, ['content-type' => 'text/html; charset=utf-8'], $html);
   }

   /**
    * @param array<string, mixed> $data
    */
   protected function renderPage(string $title, string $template, array $data = []): string
   {
      $content = $this->views->render($template, $data);

      return $this->views->render('layout', [
         'title' => $title,
         'content' => $content,
         'username' => $data['username'] ?? 'Guest',
      ]);
   }

   /**
    * @return array{first_name:string,last_name:string,phone:string,address:string,age:string}
    */
   protected function inputValues(Request $request): array
   {
      $body = $request->getParsedBody();
      if (!is_array($body)) {
         $raw = $request->getBody();
         if ($raw !== '') {
            $parsed = [];
            parse_str($raw, $parsed);
            if (is_array($parsed)) {
               $body = $parsed;
            }
         }
      }

      if (!is_array($body)) {
         return [
            'first_name' => '',
            'last_name' => '',
            'phone' => '',
            'address' => '',
            'age' => '',
         ];
      }

      return [
         'first_name' => trim((string) ($body['first_name'] ?? '')),
         'last_name' => trim((string) ($body['last_name'] ?? '')),
         'phone' => trim((string) ($body['phone'] ?? '')),
         'address' => trim((string) ($body['address'] ?? '')),
         'age' => trim((string) ($body['age'] ?? '')),
      ];
   }

   /**
    * @param array{first_name:string,last_name:string,phone:string,address:string,age:string} $values
    * @return array<string, mixed>
    */
   protected function servicePayload(array $values): array
   {
      return [
         'firstName' => $values['first_name'],
         'lastName' => $values['last_name'],
         'phone' => $values['phone'],
         'address' => $values['address'],
         'age' => $values['age'],
      ];
   }

   /**
    * @param array{first_name:string,last_name:string,phone:string,address:string,age:string} $values
    */
   protected function renderFormError(string $title, string $action, string $submitLabel, array $values, string $error): Response
   {
      $html = $this->renderPage($title, 'contacts/form', [
         'mode' => $action === '/contacts/create' ? 'create' : 'edit',
         'submitLabel' => $submitLabel,
         'action' => $action,
         'values' => $values,
         'error' => $error,
      ]);

      return new Response(422, ['content-type' => 'text/html; charset=utf-8'], $html);
   }

   protected function redirect(string $location): Response
   {
      return new Response(302, ['location' => $location], '');
   }
}
