<?php

declare(strict_types=1);

namespace App\Http\Controllers\Base;

use Celeris\Framework\Http\Response;
use Celeris\Framework\Routing\Attribute\Route;
use Celeris\Framework\View\TemplateRendererInterface;

/**
 * @generated by Celeris scaffolding. Do not edit directly.
 * Extend this class in `App\Http\Controllers\HomePageController`.
 */
class HomePageControllerBase
{
   public function __construct(
      protected TemplateRendererInterface $views,
   ) {}

   #[Route(methods: ['GET'], path: '/', summary: 'Welcome page')]
   public function index(): Response
   {
      $content = $this->views->render('welcome');

      $html = $this->views->render('layout', [
         'title' => 'Welcome to Celeris',
         'content' => $content,
         'username' => 'Guest',
      ]);

      return new Response(200, ['content-type' => 'text/html; charset=utf-8'], $html);
   }
}
